/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "PrintApplication.h"

void main(int argc, char *argv[]) {

	[PrintApplication new];
	[NXApp run];
	[NXApp free];
	exit(0);
}
