#!/bin/csh
###
###Autogenerated Clean-up script written by setupMT.c
###

set argc=$#argv

if( $argc != 1 ) then
  echo requires 1 argument got $argc 
  echo options: l or lite - deletes all files except plots and results 
  echo          a or all  - deletes all files except setupMT.csh 
  exit(-1)
else
  set cmdlinearg=${1}
  if( $cmdlinearg == "lite" || $cmdlinearg == "l" ) then
    set clean_level=1
  else if( $cmdlinearg == "all" || $cmdlinearg == "a" ) then
    set clean_level=2
  else
    echo unknown option
    exit(-1)
  endif
endif

if( ${clean_level} == 1 ) then
  /bin/rm -f *.glib *.ginv *.data 
  /bin/rm -f *.dat.xy *.syn.xy gmtwf.*.pdf gmtwf.*.ps 
  /bin/rm -f mtinv.out multithread_mkgrnlib.out 
  /bin/rm -f create.sql 
  /bin/rm -f plot_T*ps 
  /bin/rm -f gmtmap.csh gmtmap.ps 
  /bin/rm -f plotmap.csh 
  /bin/rm -f plotz.csh plotmech.csh results.?.??? 
  /bin/rm -f gmt.conf gmt.history 
endif

if( ${clean_level} == 2 ) then
  /bin/rm -f *.glib *.ginv *.data 
  /bin/rm -f *.dat.xy *.syn.xy
  /bin/rm -f gmtwf.csh gmtwf.*.pdf gmtwf.*.ps gmtwf.*.jpg 
  /bin/rm -f mtinv.out multithread_mkgrnlib.out 
  /bin/rm -f db.txt automt.txt index.html snr.out var_red.out
  /bin/rm -f *.par 
  /bin/rm -f insert.sql 
  /bin/rm -f create.sql 
  /bin/rm -f plot_T*.ps 
  /bin/rm -f email_T*.txt 
  /bin/rm -f plot_T*.jpg 
  /bin/rm -f gmtmap.csh gmtmap.ps gmtmap.jpg
  /bin/rm -f plotmap.csh sac2gmtmap.jpg
  /bin/rm -f plotmech.??? plotz.csh plotz.jpg results.?.??? 
  /bin/rm -f exclude.sta exclude_sta.txt 
  /bin/rm -f llnl_db.load.txt
  /bin/rm -f gmt.conf gmt.history 
  /bin/rm -f makeglib.csh 
  /bin/rm -f run.csh 
  /bin/rm -f run2.csh 
endif
