#!/bin/csh
######################################################################
### Autogenerated C-shell script by setupMT.c                      ###
###  This C-shell script sets up mkgrnlin to create                ###
###  Green's functions from all the SAC data hdrs                  ###
######################################################################
### DataDir = (../Data)
### RespDir = (../Resp)
######################################################################

### don't forget to add ${MTINV_PATH}/bin to your executable path in the shell startup file ###

setenv MTINV_PATH /Users/ichinose1/Work/mtinv.v4.0.1

echo " MTINV_PATH = ${MTINV_PATH} " 

### 2009/12/22T05h54m35.00 41.7392 73.377 Kambrata, Kyrgyzstan

cat >! wus.par << EOF
velmod=wus
#zrange=3,3,33
zrange=1,1,25
evla=41.7392
evlo=73.377
dt=0.15
nt=2048
fmax=0.4
t0=0.
redv=18.
damp=1.
kmax=20000
eps=0.0005
smin=0.0005
modeldb=${MTINV_PATH}/data/modeldb/
stadb=../Data/rdseed.stations
noverbose
nodump
EOF

cat >! mkgrnlib.par << EOF
### station-code network-code location-code mkgrnlib.parfile dt(sec/sample) ### comments
ARLS     KR       "" wus.par     0.050 ### R=    80 Az=080 KR.ARLS.     nchan=1 nseg=1 (BHZ)
EKS2     KN       "" wus.par     0.050 ### R=   108 Az=018 KN.EKS2.     nchan=1 nseg=1 (BHZ)
UCH      KN       "" wus.par     0.050 ### R=   108 Az=060 KN.UCH.      nchan=1 nseg=1 (BHZ)
KBK      KN       "" wus.par     0.070 ### R=   165 Az=051 KN.KBK.      nchan=1 nseg=1 (BHZ)
CHM      KN       "" wus.par     0.070 ### R=   180 Az=038 KN.CHM.      nchan=1 nseg=1 (BHZ)
USP      KN       "" wus.par     0.080 ### R=   193 Az=028 KN.USP.      nchan=1 nseg=1 (BHZ)
TKM2     KN       "" wus.par     0.100 ### R=   225 Az=053 KN.TKM2.     nchan=1 nseg=1 (BHZ)
ULHL     KN       "" wus.par     0.110 ### R=   243 Az=076 KN.ULHL.     nchan=1 nseg=1 (BHZ)
KKAR     KZ       "" wus.par     0.120 ### R=   280 Az=304 KZ.KKAR.     nchan=1 nseg=1 (BHZ)
EOF

multithread_mkgrnlib \
     parfile=mkgrnlib.par \
     executable_pathname=${MTINV_PATH}/bin/mkgrnlib > multithread_mkgrnlib.out

makepar com="Kambrata, Kyrgyzstan" \
    date="2009-12-22T05:54:35.00" \
    DataDir=../Data \
    RespDir=../Resp \
    gmt5 nooracle nomysql sqlite \
    maxsta=8 mindist=70 maxdist=800 \
    lf=0.033 hf=0.1 \
    minsnr=3.0 ctol=0.85 maxshift=10 realtime nolocal *.glib
###
### dump and plot the greens functions for single depth
###
# grnlib2sac glib=KR.ARLS."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.EKS2."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.UCH."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.KBK."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.CHM."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.USP."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.TKM2."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KN.ULHL."".wus.glib dumpgrn plotgrn z=1
# grnlib2sac glib=KZ.KKAR."".wus.glib dumpgrn plotgrn z=1
