.TH renamesac 1 "27 April 2023" "MTINV Version 4.0.1" "MTINV Toolkit"

.SH NAME 
renamesac \- renames SAC file(s)

.SH SYNOPSIS
renamesac [sacfile(s)]
.br
 
.SH DESCRIPTION
renames SAC file(s) 
.br

.SH REQUIRED PARAMETERS
a single or multiple SAC files

.SH EXAMPLE
.br
2021.322.02.48.03.0000.NM.CGM3.00.HHE.D.SAC  2021.322.02.48.03.0019.IU.CCM.00.BHZ.D.SAC
.br
2021.322.02.48.03.0000.NM.GNAR.00.HHE.D.SAC  2021.322.02.48.03.0019.IU.CCM.10.BH1.D.SAC
.br
2021.322.02.48.03.0000.NM.GNAR.00.HHN.D.SAC  2021.322.02.48.03.0019.IU.CCM.10.BH2.D.SAC

.SH "SEE ALSO"
.IR mtinv (1)
