.TH whatshere 1 "27 April 2023" "MTINV Version 4.0.1" "MTINV Toolkit"

.SH NAME 
whatshere \- lists all files in directory

.SH SYNOPSIS
whatshere
.br
 
.SH DESCRIPTION
lists diagnostic information for all MTINV (*.glib, *.ginv, *data) files in directory

.SH REQUIRED PARAMETERS

.TP
.B none

.SH OPTIONAL PARAMETERS

.TP
.B none

.SH Example output
.br


.SH "SEE ALSO"
.IR mkgrnlib (1),
.IR glib2sac (1),
.IR mtinv (1)
